[package]
name = "media-organizer-minimal"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.6.3", features = ["desktop"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[[bin]]
name = "media-organizer-minimal"
path = "src/main_minimal.rs"